algoritmo "Impar Par"
// Função :
// Autor :
// Data : 24/02/2024
// Seção de Declarações 
var
    n: inteiro
inicio
// Seção de Comandos

    escreva("Digite um numero interio: ")
    leia(n)

    se (n % 2 = 0) entao
      escreval("O numero: ",n," é par")
    senao
      escreval("\n o numero: " ,n," é impar \n")
    fimse



    escreval(" ------OBRIGADO POR USA O NOSSO PROGRAMA------------")



fimalgoritmo
